packages:
  - apps/*
  - packages/*
  - servers/auth-server
  - servers/gateway
  - servers/message-server
  - servers/realtime-hub
  - servers/call-server
  - servers/media-server
  - servers/notification-server
  - servers/relationship-server
  - servers/status-server
  - servers/search-server
  - servers/admin-server
allowBuilds:
  argon2: true
  electron: true
  esbuild: true
  redis-memory-server: true
  unrs-resolver: true
minimumReleaseAgeExclude:
  - expo-constants@57.0.17
  - expo-notifications@57.0.16
  - expo-image-picker@57.0.16
nodeLinker: hoisted
