import { Types } from "mongoose";
import { AppError } from "./auth-core/contracts.js";
import { AuthSessionModel } from "./auth-core/auth-session.model.js";
import { UserModel } from "./auth-core/user.model.js";
import { PresenceSessionModel, type PresenceSessionDocument } from "./presence.model.js";
import { isUserOnline } from "../redis.js";

function objectId(value: string): Types.ObjectId { if (!Types.ObjectId.isValid(value)) throw new AppError({ code: "PRESENCE_NOT_FOUND", message: "The requested presence history was not found.", statusCode: 404 }); return new Types.ObjectId(value); }
function duration(start: Date, end: Date): number { return Math.max(0, Math.floor((end.getTime() - start.getTime()) / 1000)); }
function dto(session: PresenceSessionDocument, now = new Date()) { return { id: session._id.toString(), startedAt: session.startedAt.toISOString(), endedAt: session.endedAt?.toISOString() ?? null, durationSeconds: session.endedAt === null ? duration(session.startedAt, now) : session.durationSeconds }; }
async function closeActive(userId: Types.ObjectId, endedAt: Date, before?: Date): Promise<PresenceSessionDocument | null> { const active = await PresenceSessionModel.findOne({ userId, endedAt: null, ...(before === undefined ? {} : { startedAt: { $lt: before } }) }).sort({ startedAt: -1 }).exec(); if (active === null) return null; return PresenceSessionModel.findOneAndUpdate({ _id: active._id, endedAt: null }, { $set: { endedAt, durationSeconds: duration(active.startedAt, endedAt) } }, { returnDocument: "after" }).exec(); }
export async function startPresence(userId: string, sessionId: string): Promise<void> { const id = objectId(userId); const now = new Date(); const recovered = await closeActive(id, now); if (recovered !== null) await UserModel.updateOne({ _id: id }, { $set: { lastSeenAt: now } }).exec(); const session = await AuthSessionModel.findOne({ userId: id, sessionId }).select({ deviceId: 1, platform: 1 }).exec(); try { await PresenceSessionModel.create({ userId: id, startedAt: now, endedAt: null, durationSeconds: 0, deviceId: session?.deviceId ?? null, platform: session?.platform ?? null }); } catch (error) { if (!isDuplicate(error)) throw error; } }
export async function endPresence(userId: string, endedAt = new Date()): Promise<void> { const id = objectId(userId); if (await isUserOnline(userId)) return; await closeActive(id, endedAt, endedAt); await UserModel.updateOne({ _id: id }, { $set: { lastSeenAt: endedAt } }).exec(); }
export async function getPresence(userId: string, requestedUserId: string, query: { cursor?: string | undefined; limit: number }): Promise<unknown> { if (userId !== requestedUserId) throw new AppError({ code: "PRESENCE_NOT_FOUND", message: "The requested presence history was not found.", statusCode: 404 }); const id = objectId(requestedUserId); const user = await UserModel.findById(id).select({ lastSeenAt: 1 }).exec(); if (user === null) throw new AppError({ code: "PRESENCE_NOT_FOUND", message: "The requested presence history was not found.", statusCode: 404 }); const online = await isUserOnline(requestedUserId); const cursor = query.cursor === undefined ? null : decode(query.cursor); const filter: Record<string, unknown> = { userId: id }; if (cursor !== null) filter.$or = [{ startedAt: { $lt: new Date(cursor.createdAt) } }, { startedAt: new Date(cursor.createdAt), _id: { $lt: new Types.ObjectId(cursor.id) } }]; const records = await PresenceSessionModel.find(filter).sort({ startedAt: -1, _id: -1 }).limit(query.limit + 1).exec(); const page = records.length > query.limit ? records.slice(0, query.limit) : records; const last = page.at(-1); return { isOnline: online, lastSeenAt: user.lastSeenAt?.toISOString() ?? null, sessions: page.map((record) => dto(record)), nextCursor: records.length > query.limit && last !== undefined ? Buffer.from(JSON.stringify({ createdAt: last.startedAt.toISOString(), id: last._id.toString() }), "utf8").toString("base64url") : null }; }
function decode(value: string): { createdAt: string; id: string } { try { const parsed = JSON.parse(Buffer.from(value, "base64url").toString("utf8")) as { createdAt?: unknown; id?: unknown }; if (typeof parsed.createdAt !== "string" || typeof parsed.id !== "string" || !Types.ObjectId.isValid(parsed.id) || Number.isNaN(new Date(parsed.createdAt).getTime())) throw new Error(); return { createdAt: parsed.createdAt, id: parsed.id }; } catch { throw new AppError({ code: "INVALID_CURSOR", message: "The pagination cursor is invalid.", statusCode: 400 }); } }
function isDuplicate(error: unknown): boolean { return typeof error === "object" && error !== null && "code" in error && error.code === 11000; }
