import { Router } from "express";
import { Types } from "mongoose";
import { z } from "zod";

import { AppError } from "../core/errors.js";
import { adminInternalServiceGuard } from "./service-auth.js";
import { ChannelModel, ChannelPostModel } from "../modules/channels/channel.model.js";
import { GroupModel } from "../modules/groups/group.model.js";
import { UserModel } from "../modules/users/user.model.js";
import { ConversationModel } from "../modules/conversations/conversation.model.js";
import { MessageModel } from "../modules/messages/message.model.js";
import { toContactUserDto } from "../modules/contacts/contact.dto.js";
import { toChannelPostDto } from "../modules/channels/channel.dto.js";

const id = z.string().regex(/^[a-f\d]{24}$/i);
const badges = z.object({ badges: z.array(z.enum(["verified", "terqivo"])).max(2).refine((values) => new Set(values).size === values.length) });
const targetSchema = z.object({ reporterId: id, targetType: z.enum(["user", "message", "group", "channel"]), targetUserId: id.optional(), conversationId: id.optional(), messageId: id.optional(), groupId: id.optional(), channelId: id.optional() });

function notFound(code: string, message: string): AppError { return new AppError({ code, message, statusCode: 404 }); }

export function createAdminRouter(): Router {
  const router = Router();
  router.use(adminInternalServiceGuard);
  router.get("/stats", async (_request, response, next) => { try { const start = new Date(); start.setUTCHours(0, 0, 0, 0); const [conversations, messages, today] = await Promise.all([ConversationModel.countDocuments(), MessageModel.countDocuments(), MessageModel.countDocuments({ createdAt: { $gte: start } })]); response.json({ success: true, data: { conversations: { total: conversations }, messages: { total: messages, today } } }); } catch (error) { next(error); } });
  router.get("/groups", async (_request, response, next) => { try { const groups = await GroupModel.find().sort({ updatedAt: -1, _id: -1 }).limit(500).exec(); const ids = [...new Set(groups.flatMap((group) => [group.ownerId, ...group.memberIds].map(String)))].map((value) => new Types.ObjectId(value)); const users = await UserModel.find({ _id: { $in: ids } }).exec(); const byId = new Map(users.map((user) => [user._id.toString(), user])); response.json({ success: true, data: { groups: groups.map((group) => { const owner = byId.get(group.ownerId.toString()); return { id: group._id.toString(), name: group.name, description: group.description, avatarUrl: group.avatarUrl, badges: group.badges ?? [], owner: owner === undefined ? null : toContactUserDto(owner), admins: owner === undefined ? [] : [toContactUserDto(owner)], members: group.memberIds.flatMap((memberId) => { const user = byId.get(memberId.toString()); return user === undefined ? [] : [toContactUserDto(user)]; }), memberCount: group.memberIds.length, createdAt: group.createdAt.toISOString(), updatedAt: group.updatedAt.toISOString() }; }) } }); } catch (error) { next(error); } });
  router.get("/channels", async (_request, response, next) => { try { const channels = await ChannelModel.find().sort({ updatedAt: -1, _id: -1 }).limit(500).exec(); const posts = channels.length === 0 ? [] : await ChannelPostModel.find({ channelId: { $in: channels.map((channel) => channel._id) } }).sort({ createdAt: -1, _id: -1 }).limit(1000).exec(); const ids = [...new Set(channels.flatMap((channel) => [channel.ownerId, ...channel.followerIds]).concat(posts.map((post) => post.authorId)).map(String))].map((value) => new Types.ObjectId(value)); const users = await UserModel.find({ _id: { $in: ids } }).exec(); const byId = new Map(users.map((user) => [user._id.toString(), user])); const latest = new Map<string, typeof posts[number]>(); for (const post of posts) if (!latest.has(post.channelId.toString())) latest.set(post.channelId.toString(), post); response.json({ success: true, data: { channels: channels.map((channel) => { const owner = byId.get(channel.ownerId.toString()); const post = latest.get(channel._id.toString()); const author = post === undefined ? undefined : byId.get(post.authorId.toString()); return { id: channel._id.toString(), name: channel.name, handle: channel.handle, description: channel.description, avatarUrl: channel.avatarUrl, badges: channel.badges ?? [], owner: owner === undefined ? null : toContactUserDto(owner), followers: channel.followerIds.flatMap((followerId) => { const user = byId.get(followerId.toString()); return user === undefined ? [] : [toContactUserDto(user)]; }), followerCount: channel.followerIds.length, latestPost: post === undefined || author === undefined ? null : toChannelPostDto(post, author), createdAt: channel.createdAt.toISOString(), updatedAt: channel.updatedAt.toISOString() }; }) } }); } catch (error) { next(error); } });
  router.patch("/groups/:groupId/badges", async (request, response, next) => { try { const groupId = id.parse(request.params.groupId); const group = await GroupModel.findById(groupId).exec(); if (group === null) throw notFound("ADMIN_GROUP_NOT_FOUND", "The group was not found."); group.badges = badges.parse(request.body).badges; await group.save(); response.json({ success: true, data: { updated: true, badges: group.badges } }); } catch (error) { next(error); } });
  router.patch("/channels/:channelId/badges", async (request, response, next) => { try { const channelId = id.parse(request.params.channelId); const channel = await ChannelModel.findById(channelId).exec(); if (channel === null) throw notFound("ADMIN_CHANNEL_NOT_FOUND", "The channel was not found."); channel.badges = badges.parse(request.body).badges; await channel.save(); response.json({ success: true, data: { updated: true, badges: channel.badges } }); } catch (error) { next(error); } });
  router.post("/report-target/validate", async (request, response, next) => { try { const input = targetSchema.parse(request.body); if (input.targetUserId !== undefined && await UserModel.exists({ _id: new Types.ObjectId(input.targetUserId), accountStatus: "active" }) === null) throw notFound("REPORT_TARGET_NOT_FOUND", "The reported user was not found."); if (input.conversationId !== undefined && await ConversationModel.exists({ _id: new Types.ObjectId(input.conversationId), "participants.userId": new Types.ObjectId(input.reporterId) }) === null) throw notFound("CONVERSATION_NOT_FOUND", "The conversation was not found."); if (input.messageId !== undefined) { const message = await MessageModel.findOne({ _id: new Types.ObjectId(input.messageId), ...(input.conversationId === undefined ? {} : { conversationId: new Types.ObjectId(input.conversationId) }) }).select({ conversationId: 1 }).exec(); if (message === null) throw notFound("REPORT_TARGET_NOT_FOUND", "The reported message was not found."); if (input.conversationId === undefined && await ConversationModel.exists({ _id: message.conversationId, "participants.userId": new Types.ObjectId(input.reporterId) }) === null) throw notFound("CONVERSATION_NOT_FOUND", "The conversation was not found."); } if (input.groupId !== undefined && await GroupModel.exists({ _id: new Types.ObjectId(input.groupId), memberIds: new Types.ObjectId(input.reporterId) }) === null) throw notFound("REPORT_TARGET_NOT_FOUND", "The reported group was not found."); if (input.channelId !== undefined && await ChannelModel.exists({ _id: new Types.ObjectId(input.channelId) }) === null) throw notFound("REPORT_TARGET_NOT_FOUND", "The reported channel was not found."); response.json({ success: true, data: { valid: true } }); } catch (error) { next(error); } });
  return router;
}
