import type { AdminUserDocument } from "../../models/admin-user.js";
import type { AdminUserDto, AdminUserListItemDto, AdminUserAppVersionDto, ContactDto, AdminReportDto, ReportDto } from "./contracts.js";
import type { ReportDocument } from "../../models/report.js";

export interface PublicUserSnapshot { id: string; username: string; displayName: string; phone?: string | null; avatarUrl?: string | null; bio?: string | null; accountType?: "personal" | "professional" | "business"; badges?: ("verified" | "terqivo")[]; }

export function toAdminUserDto(admin: AdminUserDocument): AdminUserDto { return { id: admin._id.toString(), email: admin.emailNormalized, displayName: admin.displayName, role: admin.role, permissions: admin.permissions, lastLoginAt: admin.lastLoginAt?.toISOString() ?? null, createdAt: admin.createdAt.toISOString() }; }
export function toContactDto(user: PublicUserSnapshot): ContactDto { return { id: user.id, username: user.username, displayName: user.displayName, phone: user.phone ?? null, avatarUrl: user.avatarUrl ?? null, bio: user.bio ?? null, accountType: user.accountType ?? "personal", badges: user.badges ?? [] }; }
export function toAdminUserListItemDto(user: PublicUserSnapshot & { email?: string | null; accountStatus: "active" | "suspended" | "disabled"; role: "user" | "moderator" | "admin"; userTier: "normal" | "special" | "special_pro" | "ultra_special"; createdAt: string; lastSeenAt: string | null }, appVersions: AdminUserAppVersionDto[]): AdminUserListItemDto { return { id: user.id, username: user.username, displayName: user.displayName, email: user.email ?? null, phone: user.phone ?? null, avatarUrl: user.avatarUrl ?? null, accountStatus: user.accountStatus, role: user.role, accountType: user.accountType ?? "personal", userTier: user.userTier ?? "normal", badges: user.badges ?? [], createdAt: user.createdAt, lastSeenAt: user.lastSeenAt, appVersions }; }
export function toReportDto(report: ReportDocument): ReportDto { return { id: report._id.toString(), targetType: report.targetType, conversationId: report.conversationId?.toString() ?? null, messageId: report.messageId?.toString() ?? null, groupId: report.groupId?.toString() ?? null, channelId: report.channelId?.toString() ?? null, reason: report.reason, details: report.details, status: report.status, createdAt: report.createdAt.toISOString(), updatedAt: report.updatedAt.toISOString() }; }
export function toAdminReportDto(report: ReportDocument, reporter: PublicUserSnapshot | undefined, targetUser: PublicUserSnapshot | undefined): AdminReportDto { return { ...toReportDto(report), reporter: reporter === undefined ? { id: report.reporterId.toString(), username: "unknown", displayName: "Unknown user" } : { id: reporter.id, username: reporter.username, displayName: reporter.displayName }, targetUser: targetUser === undefined ? null : { id: targetUser.id, username: targetUser.username, displayName: targetUser.displayName }, resolvedByAdminId: report.resolvedByAdminId?.toString() ?? null, resolvedAt: report.resolvedAt?.toISOString() ?? null }; }
